### ISSUE TITLE
Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ronoren** [akashrchandran/syrics#11]
I tried to run the script and got this error:

Traceback (most recent call last):
  File "C:\Users\Ron Oren\syrics\syrics.py", line 31, in <module>
    cmd_url = parse_cmd(config, client)
  File "C:\Users\Ron Oren\syrics\cli.py", line 29, in parse_cmd
    args.URL = client.get_current_song(
TypeError: 'NoneType' object is not subscriptable
PS C:\Users\Ron Oren\syrics>

I did everything right, renamed the config file and got the sp_dc but for some reason I can't even get the script started.
Love to get help on this.
Thanks!

**Comment by akashrchandran** [comment]
> I did everything right, renamed the config file and got the sp_dc but for some reason I can't even get the script started. Love to get help on this. Thanks!
Could you please check now, I have made a fix.

**Comment by ronoren** [comment]
Yeah, it's fixed now.
Great tool, thanks!
