### ISSUE TITLE
unable to create folders

### ISSUE THREAD

**Issue by evafans** [akashrchandran/syrics#12]
Folders are not created, and lrc not properly named.
![QQ截图20220917214612](https://user-images.githubusercontent.com/88836421/190860210-d096e5c0-65bb-4d69-afac-04480f6cda4e.png)

**Comment by akashrchandran** [comment]
I have made some changes, please update to new version and verify. To [update you can check wiki](https://github.com/akashrchandran/syrics/wiki/Installation#updating).

**PS: Made some changes to config file structure, so you will need to delete the old config and rename `sample_config.json` to `config.json` and then set all your preferences.**
