### ISSUE TITLE
Limit to 50 tracks

### ISSUE THREAD

**Issue by ronoren** [akashrchandran/syrics#13]
![Screenshot_20220921-130638_Termux](https://user-images.githubusercontent.com/11407141/191477399-ca1a6bcf-02a3-4de3-b777-ba41f2f4c0d5.png)

**Comment by akashrchandran** [comment]
Thanks for raising this issue, I had totally forgot about requests limits of the Spotify API. I have made a fix, please update and verify. To update you can check the [wiki page](https://github.com/akashrchandran/syrics/wiki/Installation#updating).

**Comment by ronoren** [comment]
50+  work but I tried a big playlist with over 1000 tracks and it gave that error:
![Screenshot_20220922-180446_Termux](https://user-images.githubusercontent.com/11407141/191783425-8306cd31-fa03-4188-a4e2-00b3499ffacf.jpg)

**Comment by akashrchandran** [comment]
**_It's seems that the problem is caused by a track which is no longer available on Spotify. I will try to fix it as soon as possible._**
![image](https://user-images.githubusercontent.com/78685510/191816621-3a0c1361-1a9b-41ce-ad99-74768dbe0c58.png)

**Comment by akashrchandran** [comment]
@ronoren I have updated, you may try it.

**Comment by ronoren** [comment]
It is working now!🙌
