### ISSUE TITLE
New Update Give Errors

### ISSUE THREAD

**Issue by ronoren** [akashrchandran/syrics#21]
Congrats on the new update!
It looks promising, but it does have few bugs:

I installed the new program with pip install and run a "syrics --config" commend.
Here's who it turned out:

![image](https://user-images.githubusercontent.com/11407141/194848234-be85496a-45c4-4d77-ab18-61dc4665792b.png)

**Comment by akashrchandran** [comment]
That's really a dumb mistake to make lol 🥲

**Comment by abijithka678** [comment]
Please Assign me i can solve the issue

**Comment by akashrchandran** [comment]
New updated version has been released, you can update by doing  `pip install syrics --upgrade`
