### ISSUE TITLE
ID Tags

### ISSUE THREAD

**Issue by remlap** [akashrchandran/syrics#27]
Could it be possible to add ID Tags? Example:

```
[ar:Chubby Checker oppure  Beatles, The]
[al:Hits Of The 60's - Vol. 2 – Oldies]
[ti:Let's Twist Again]
[au:Written by Kal Mann / Dave Appell, 1961]
[length: 2:23]

[00:12.00]Naku Penda Piya-Naku Taka Piya-Mpenziwe
[00:15.30]Some more lyrics ..
```
Thank you for this tool!

**Comment by akashrchandran** [comment]
A great suggestion will be easy to add. The only problem is that some of the tags like ` [ar:Lyrics artist] ` details isn't provided by the Spotify API. Rest I will add.

**Comment by akashrchandran** [comment]
I have added it https://github.com/akashrchandran/syrics/commit/4289c4d834f9782373cb6162518e9814bcb917b8, please check it and let me know.

**Comment by remlap** [comment]
> I have added it [4289c4d](https://github.com/akashrchandran/syrics/commit/4289c4d834f9782373cb6162518e9814bcb917b8), please check it and let me know.

Working well, thank you.
