### ISSUE TITLE
Installation failed on latest python (termux)

### ISSUE THREAD

**Issue by SimplyVoid** [akashrchandran/syrics#28]
This used to work really well on termux before but today i reinstalled termux and it's not even installing,
seems like it tries to update pip through it's installation script which is causing the issue.. Other packages work fine that's why I'm opening this issue here.

![Screenshot_20230227-052753](https://user-images.githubusercontent.com/75927811/221444024-8b6cd92f-3d88-4be2-ad79-77df77b1ff67.png)

**Comment by akashrchandran** [comment]
Sorry for the late reply.

I think it's something to do with `pip`, with older version of pip it works fine. I think the best work around is to just to create a virtual environment.

```bash
python3 -m venv .venv
source .venv/bin/activate
```

**Comment by akashrchandran** [comment]
Closing the issue because of no response.
