### ISSUE TITLE
How to disable config setup at the first run?

### ISSUE THREAD

**Issue by micash545** [akashrchandran/syrics#29]
When I run my script with the Syrics module for the first time, I get the config setup. Can I disable it?

**Comment by akashrchandran** [comment]
I don't get why you want to disable that. Without the config set-up the program will not work. If you're facing any problem with setting up config please say.

**Comment by micash545** [comment]
or how to set config inside my script

**Comment by akashrchandran** [comment]
I apologize for not understanding your question initially. I have addressed the issue you raised, and you may verify that the changes have been implemented to your satisfaction. Thank you for bringing this to my attention; it was an important matter that needed to be resolved.

You'll require to update the module.

https://github.com/akashrchandran/syrics/wiki/Installation#updating

and then you can use it as a module

 ### Use as a module 
  
 ```python 
 from syrics.api import Spotify 
 sp = Spotify("SP_DC here!") 
print("Logged In as:", sp.getme()["display_name"])
 sp.get_lyrics("28RQx5pH9T9LZXY02IheWc") 
 ```
