### ISSUE TITLE
Config Corrupted 

### ISSUE THREAD

**Issue by RizkyM2999** [akashrchandran/syrics#31]
How to fix this i and can't reset config
![Uploading Screenshot_20230502-124018_Termux.png…]()

**Comment by RizkyM2999** [comment]
![Screenshot_20230502-124018_Termux](https://user-images.githubusercontent.com/44426590/235589130-0c5b136e-1e76-49a3-965b-16fc6b2b310a.png)

**Comment by akashrchandran** [comment]
Did you try resetting the config file? If you did and still ran into error, then please upload the screenshot of the errors.

You can reset the config file using the command.
```
syrics -c reset
```

**Comment by akashrchandran** [comment]
Sorry for the late reply, been busy Irl. I have fixed the issue you have to upgrade to the new version. For that you can check the docs or follow this [link](https://github.com/akashrchandran/syrics/wiki/Installation#updating).

**Comment by akashrchandran** [comment]
> > Sorry for the late reply, been busy Irl. I have fixed the issue; you will have to upgrade to the new version. For that you can check the docs or follow this [link](https://github.com/akashrchandran/syrics/wiki/Installation#updating).
> 
> Now i get this error !

Oops, I made a mistake. Sorry about that! I only needed to change a single line of code, but I ended up pushing it without changing. It should work now, you will need to upgrade the package again.

**Comment by RizkyM2999** [comment]
Ok it's working now..
But when I change the file format to artists-name i get this error
![Screenshot_20230504-113058_Termux](https://user-images.githubusercontent.com/44426590/236113279-e747beb6-d09e-4f9e-b3d2-aa7faa8cbb3e.png)
