### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by BeBeeMan** [akashrchandran/syrics#7]
I think i would be cool if you could get the lyrics of the song you are currently listening to automatically downloaded. (I have seen that this function exist but it is not used anywhere) 👍

**Comment by akashrchandran** [comment]
> I think i would be cool if you could get the lyrics of the song you are currently listening to automatically downloaded. (I have seen that this function exist but it is not used anywhere) +1

Thanks for opening the issue. I had made that function for the same reason but was just procrastinating for lazy reasons. I have implemented, haven't updated the readme (will work on it) just read the pull requests description.
